#1
kind: pipeline
type: docker
name: CI Process
steps:
  - name: 通过 npm 进行 package
    image: node:12.22.7
    environment:
      modulePath:
    commands:
      - npm config set prefix "/var/lib/node_modules"
      - npm config set registry=https://registry.npmmirror.com
      - npm install --unsafe-perm
      - npm cache clean --force
      - npm run translate
      - npm run build
    volumes:
      - name: cache # The Volume's name
        path: /root/.npm # The path in the container
      - name: node
        path: /drone/src/node_modules
    when:
      status: [success]
  - name: 版本控制
    image: registry.digiwincloud.com.cn/base/base_vc
    commands:
      - make branch=$DRONE_TARGET_BRANCH vc # $DRONE_TARGET_BRANCH这个参数是当前打包分支
    when:
      status: [success]
  - name: 上傳版本
    image: registry.digiwincloud.com.cn/base/base_vc
    commands:
      - make branch=$DRONE_TARGET_BRANCH to_git
    when:
      status: [success]
  - name: 打包與推送 Docker Image
    image: plugins/docker
    settings:
      username:
        from_secret: dockerUsername
      password:
        from_secret: dockerPassword
      repo: registry.digiwincloud.com.cn/athena/pccpackage
      registry: registry.digiwincloud.com.cn
      experimental: true
    when:
      status: [success]
  - name: 钉钉通知
    image: guoxudongdocker/drone-dingtalk
    settings:
      token:
        from_secret: dingTalkToken
      type: markdown
      message_color: true
      message_pic: true
      sha_link: true
    when:
      status: [failure, success]
trigger:
  branch:
    - feature/2023-S4
    - hotfix/2023-S3
    - release
    - develop
    - master
  event:
    - push
    - pull_request
    - cron
volumes:
  - name: cache
    host:
      path: /var/lib/cache/npm-test
  - name: node
    host:
      path: /data/package/node_modules
