stages:
  - lib
  - project
  - pages

release-framework:
  stage: lib
  script:
    - npm install
    - npm run build @webdpt/framework
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    expire_in: "2 days"
    untracked: false
    paths:
      - dist/webdpt/framework
  only:
    - master

release-project:
  stage: project
  script:
    - rm -rf projects/webdpt/framework
    - mv dist/webdpt/framework projects/webdpt
    - node projects/webdpt/builds/rewrite-package.js
    - rm -rf projects/webdpt/builds
    - rm -rf node_modules
    - rm -rf .git
    - rm -rf dist
  artifacts:
    name: "ng-webdpt"
    expire_in: "2 days"
    untracked: false
    paths:
      - ./
  only:
    - master

pages:
  stage: pages
  script:
    - npm install
    - npm run build showcase-app -- --base-href /$CI_PROJECT_NAME/ --output-path public
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public/
  only:
    - develop
