

export const MonthList: String[] = [
  '一月',
  '二月',
  '三月',
  '四月',
  '五月',
  '六月',
  '七月',
  '八月',
  '九月',
  '十月',
  '十一月',
  '十二月',
];

export const TwLocaleConfigDate: any =  {
  month_full: [
    '一月',
    '二月',
    '三月',
    '四月',
    '五月',
    '六月',
    '七月',
    '八月',
    '九月',
    '十月',
    '十一月',
    '十二月',
  ],
  month_short: [
    '1月',
    '2月',
    '3月',
    '4月',
    '5月',
    '6月',
    '7月',
    '8月',
    '9月',
    '10月',
    '11月',
    '12月',
  ],
  day_full: ['星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六'],
  day_short: ['日', '一', '二', '三', '四', '五', '六'],
};

export const TwLocaleConfigLabels: any =  {
  new_task: '新任務',
  icon_save: '保存',
  icon_cancel: '取消',
  icon_details: '詳情',
  icon_edit: '編輯',
  icon_delete: '刪除',
  gantt_save_btn: '保存',
  gantt_cancel_btn: '取消',
  gantt_delete_btn: '刪除',
  confirm_closing: '您尚未保存任務，確定關閉嗎？', // Your changes will be lost, are you sure?
  confirm_deleting: '任務將永久刪除，請確認？',
  section_description: '描述',
  section_time: '持續時間',
  section_type: '類型',
  /* grid columns */
  column_wbs: 'WBS名稱',
  column_text: '任務名稱',
  column_start_date: '開始時間',
  column_duration: '持續時間',
  column_add: '',
  /* link confirmation */
  link: '鏈接',
  confirm_link_deleting: '鏈接將被刪除，請確認',
  link_start: ' (開始)',
  link_end: ' (結束)',
  type_task: '任務',
  type_project: '項目',
  type_milestone: '裏程碑',
  minutes: '分鐘',
  hours: '小時',
  days: '天',
  weeks: '周',
  months: '月',
  years: '年',
  /* message popup */
  message_ok: '確認',
  message_cancel: '取消',
  /* constraints */
  section_constraint: '約束',
  constraint_type: '約束類型',
  constraint_date: '約束日期',
  asap: '儘快完成',
  alap: '盡可能晚完成',
  snet: '開始不早于',
  snlt: '開始不晚於',
  fnet: '完成不早於',
  fnlt: '完成不晚於',
  mso: '必須開始在',
  mfo: '必須完成在',
  /* resource control */
  resources_filter_placeholder: '輸入以篩選',
  resources_filter_label: '隱藏空值',
};

// export const taskData = [
//   {
//     name: 'plan_work_hours',
//     label: this.translateService.instant('dj-default-预计工时'),
//     align: 'center',
//     resize: true,
//   },
//   {
//     name: 'actual_work_hours',
//     label: this.translateService.instant('dj-default-实际工时'),
//     align: 'center',
//     resize: true,
//   },
//   {
//     name: 'complete_rate',
//     label: this.translateService.instant('dj-default-完成率'),
//     align: 'center',
//     resize: true,
//   },
//   {
//     name: 'remaining_work_hours',
//     label: this.translateService.instant('dj-default-剩余工时'),
//     align: 'center',
//     resize: true,
//   },
//   {
//     name: 'work_hours_difference',
//     label: this.translateService.instant('dj-default-工时差异'),
//     align: 'center',
//     resize: true,
//     template: this.workHoursDifferenceCss,
//   },
//   {
//     name: 'time_out_status',
//     label: this.translateService.instant('dj-default-超时状态'),
//     align: 'center',
//     resize: true,
//   },
//   {
//     name: 'overdue_days',
//     label: this.translateService.instant('dj-default-延迟天数'),
//     align: 'center',
//     resize: true,
//     template: this.overdueDays,
//   },
//   {
//     name: 'schedule_status',
//     label: this.translateService.instant('dj-default-时程状态'),
//     align: 'center',
//     resize: true,
//   },
//   {
//     name: 'liable_person_department_name',
//     label: this.translateService.instant('dj-default-部门'),
//     align: 'center',
//     resize: true,
//   },
//   {
//     name: 'liable_person_name',
//     label: this.translateService.instant('dj-default-负责人'),
//     align: 'center',
//     resize: true,
//   },
//   {
//     name: 'start_date',
//     label: this.translateService.instant('dj-default-计划开始时间'),
//     align: 'center',
//     resize: true,
//   },
//   {
//     name: 'plan_finish_date',
//     label: this.translateService.instant('dj-default-计划结束时间'),
//     align: 'center',
//     resize: true,
//   },
//   {
//     name: 'actual_start_date',
//     label: this.translateService.instant('dj-default-实际开始时间'),
//     align: 'center',
//     resize: true,
//   },
//   {
//     name: 'actual_finish_date',
//     label: this.translateService.instant('dj-default-实际结束时间'),
//     align: 'center',
//     resize: false,
//   }
// ];
