#2
kind: pipeline
type: docker
name: CI Process
steps:
  - name: npm package
    image: node:14.21.1
    environment:
      modulePath:
    commands:
      - npm config set prefix "/var/lib/node_modules"
      - npm config set registry=https://registry.npmmirror.com
      - npm install --unsafe-perm
      - npm cache clean --force
      - npm run translate
      - npm run build
    volumes:
      - name: cache # The Volume's name
        path: /root/.npm # The path in the container
      - name: node
        path: /drone/src/node_modules
    when:
      status: [success]
  - name: version control
    image: registry.digiwincloud.com.cn/base/base_vc
    commands:
      - make -C version_control branch=$DRONE_TARGET_BRANCH # $DRONE_TARGET_BRANCH这个参数是当前打包分支
    when:
      status: [success]
  - name: athena publish docker image
    image: plugins/docker
    settings:
      username:
        from_secret: tigerUsername
      password:
        from_secret: tigerPassword
      repo: registry.digiwincloud.com.cn/tiger/pccpackage
      registry: registry.digiwincloud.com.cn
      experimental: true
    when:
      status: [success]
  - name: 钉钉通知
    image: guoxudongdocker/drone-dingtalk
    settings:
      token:
        from_secret: dingTalkToken
      type: markdown
      message_color: true
      message_pic: true
      sha_link: true
    when:
      status: [failure, success]
trigger:
  branch:
    - test
    - feature/2024-i05

  event:
    - push
    - pull_request
    - cron
volumes:
  - name: cache
    host:
      path: /var/lib/cache/npm-test
  - name: node
    host:
      path: /data/package/pcc_package/node_modules
