import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { DwSystemConfigService } from '@webdpt/framework/config';
import { TranslateService } from '@ngx-translate/core';
import { map } from 'rxjs/operators';
import { Subject } from 'rxjs';
import { CommonService, Entry } from 'app/implementation/service/common.service';

@Injectable()
export class ListOfDeliverableV2Service {
  uibotUrl: string;
  // 记录机制的content参数
  content: any;
  // 开窗所需参数
  source: Entry = Entry.card;
  executeContext: any;
  OpenWindowDefine: any; // 开窗定义
  smartDataUrl: string;
  outputSubject = new Subject();
  batchDownloadsData = new Set();
  constructor(
    private http: HttpClient,
    private configService: DwSystemConfigService,
    protected translateService: TranslateService,
    public commonService: CommonService
  ) {
    this.configService.get('uibotUrl').subscribe((url: string): void => {
      this.uibotUrl = url;
    });
    this.configService.get('smartDataUrl').subscribe((url: string) => {
      this.smartDataUrl = url;
    });
  }
  // 提供一个方法用于订阅输出事件
  subscribeToOutput() {
    return this.outputSubject.asObservable();
  }
  // 方法用于发送输出事件
  sendOutputEvent(data: any) {
    this.outputSubject.next(data);
  }
  completeOutputEvent() {
    this.outputSubject.complete();
  }
  getDeliverableData(params: any) {
    // const header = {
    //   headers: {
    //     'digi-service': JSON.stringify({
    //       prod: 'PCC',
    //       ip: 'pcc-test.apps.digiwincloudlocal.com.cn',
    //       id: 'PCC',
    //       uid: 'PCC',
    //       name: 'project.attachment.get',
    //       ver: '1.0',
    //       tenant_id: 'DCP',
    //     }),
    //     'digi-host': JSON.stringify({
    //       prod: 'Athena',
    //       ip: 'esp-test.apps.digiwincloudlocal.com.cn',
    //       id: 'AgileInteraction',
    //       uid: 'agileinteraction',
    //       ver: '1.0',
    //       timestamp: '20240410155550746',
    //       lang: 'zh_CN',
    //       acct: 'athena',
    //     }),
    //     'digi-datakey': JSON.stringify({ __PtxId: 'HW_TEST_atdm-vpmdw^1711110543937^1002719' }),
    //   },
    // };
    // return this.http
    //   .post(
    //     '/api/eai',
    //     {
    //       std_data: {
    //   parameter: {
    //     query_scope: params.query_scope, // 1、任务附件  2、项目附件  3、项目变更附件  ALL、全部
    //     project_info: [
    //       {
    //         project_no: params.project_no,
    //       },
    //     ],
    //   },
    // },
    //     },
    //     header as any
    //   )
    //   .pipe(
    //     map((res: any) => {
    //       return (
    //         res.std_data.parameter || {
    //           'projectInfoList ms:': 35817.87425,
    //           task_attachment: [
    //             {
    //               task_name: 'A',
    //               is_root_task: true,
    //               upper_level_task_no: '1',
    //               moh_attachment: [],
    //               task_no: '1',
    //               manual_assignment_delivery_plm: [],
    //               pcc_wbs_plan_changes: [],
    //               manual_assignment_delivery: [],
    //               root_task_no: '1',
    //               manual_assignment_attachment: [],
    //               sequence: 1,
    //               moh_deliverable: [],
    //               project_no: '20240410000001',
    //               is_last_level: false,
    //             },
    //             {
    //               task_name: 'A1',
    //               manual_assignment_sample_delivery: [
    //                 {
    //                   category_id: 'manualAssignmentSampleDelivery',
    //                   size: 0,
    //                   upload_user_id: 'dcp012',
    //                   name: '交付物样板.txt',
    //                   id: '840f05b5-bcb6-46f7-8303-5f4e0c9c3bf5',
    //                   upload_user_name: '采购员小白',
    //                   row_data: 'LPC20240410001;undefined',
    //                   category: 'manualAssignmentSampleDelivery',
    //                   create_date: '2024-04-10 15:34:06',
    //                 },
    //                 {
    //                   category_id: 'manualAssignmentSampleDelivery',
    //                   size: 0,
    //                   upload_user_id: 'dcp012',
    //                   name: '交付物样板.txt',
    //                   id: '315622c0-c12a-48c6-9645-d9dd0e55deac',
    //                   upload_user_name: '采购员小白',
    //                   row_data: '20240410000001;5',
    //                   category: 'manualAssignmentSampleDelivery',
    //                   create_date: '2024-04-10 16:30:29',
    //                 },
    //               ],
    //               is_root_task: false,
    //               upper_level_task_no: '1',
    //               moh_attachment: [],
    //               task_no: '5',
    //               manual_assignment_delivery_plm: [],
    //               pcc_wbs_plan_changes: [],
    //               manual_assignment_delivery: [],
    //               root_task_no: '1',
    //               manual_assignment_attachment: [],
    //               sequence: 1,
    //               moh_deliverable: [],
    //               project_no: '20240410000001',
    //               is_last_level: false,
    //             },
    //             {
    //               task_name: 'A2',
    //               is_root_task: false,
    //               upper_level_task_no: '1',
    //               moh_attachment: [],
    //               task_no: '7',
    //               manual_assignment_delivery_plm: [],
    //               pcc_wbs_plan_changes: [],
    //               manual_assignment_delivery: [],
    //               root_task_no: '1',
    //               manual_assignment_attachment: [],
    //               sequence: 2,
    //               moh_deliverable: [],
    //               project_no: '20240410000001',
    //               is_last_level: false,
    //             },
    //             {
    //               task_name: 'A2-1',
    //               manual_assignment_sample_delivery: [
    //                 {
    //                   category_id: 'manualAssignmentSampleDelivery',
    //                   size: 0,
    //                   upload_user_id: 'dcp012',
    //                   name: '交付物样板.txt',
    //                   id: 'e41b1de8-5779-4f38-8a88-4cd2370b6f5d',
    //                   upload_user_name: '采购员小白',
    //                   row_data: 'LPC20240410001;8',
    //                   category: 'manualAssignmentSampleDelivery',
    //                   create_date: '2024-04-10 15:47:36',
    //                 },
    //               ],
    //               is_root_task: false,
    //               upper_level_task_no: '7',
    //               moh_attachment: [],
    //               task_no: '8',
    //               manual_assignment_delivery_plm: [],
    //               pcc_wbs_plan_changes: [
    //                 {
    //                   category_id: 'pcc_wbs_planChanges',
    //                   size: 0,
    //                   upload_user_id: 'dcp012',
    //                   name: '任务变更附件.txt',
    //                   id: '1beb34d3-bb9a-4dd3-93b4-ee9ca1376e9d',
    //                   upload_user_name: '采购员小白',
    //                   row_data: '20240410000001;',
    //                   category: 'pcc_wbs_planChanges',
    //                   create_date: '2024-04-11 09:40:52',
    //                 },
    //               ],
    //               manual_assignment_delivery: [
    //                 {
    //                   category_id: 'e30a83cf-b4b9-41f6-9015-bfe9ecc3f356',
    //                   size: 0,
    //                   upload_user_id: 'dcp012',
    //                   name: '交付物.txt',
    //                   id: '8de86a09-ce08-447a-99c5-cc376db1bc94',
    //                   upload_user_name: '采购员小白',
    //                   row_data: '20240410000001;8;',
    //                   category: 'manualAssignmentDelivery',
    //                   create_date: '2024-04-10 17:44:01',
    //                 },
    //                 {
    //                   category_id: 'e30a83cf-b4b9-41f6-9015-bfe9ecc3f356',
    //                   size: 3332,
    //                   upload_user_id: 'dcp012',
    //                   name: '附件数据结构',
    //                   id: '92bdc880-aad2-4477-8e83-6b2e31bb597c',
    //                   upload_user_name: '采购员小白',
    //                   row_data: '20240410000001;8;',
    //                   category: 'manualAssignmentDelivery',
    //                   create_date: '2024-04-10 17:44:01',
    //                 },
    //               ],
    //               root_task_no: '1',
    //               manual_assignment_attachment: [
    //                 {
    //                   category_id: '3dec5e77-0489-4a7b-a97f-baf77ced1f7c',
    //                   size: 40960,
    //                   upload_user_id: 'dcp012',
    //                   name: '任务附件.dps',
    //                   id: '837a9e42-9c93-436b-8a0a-00ade8f278f1',
    //                   upload_user_name: '采购员小白',
    //                   row_data: '20240410000001;8;',
    //                   category: 'manualAssignmentAttachment',
    //                   create_date: '2024-04-10 17:44:01',
    //                 },
    //                 {
    //                   category_id: '3dec5e77-0489-4a7b-a97f-baf77ced1f7c',
    //                   size: 3332,
    //                   upload_user_id: 'dcp012',
    //                   name: '附件数据结构',
    //                   id: 'ef210a46-8466-4b0b-a606-6674aea7e7f9',
    //                   upload_user_name: '采购员小白',
    //                   row_data: '20240410000001;8;',
    //                   category: 'manualAssignmentAttachment',
    //                   create_date: '2024-04-10 17:44:01',
    //                 },
    //               ],
    //               sequence: 1,
    //               moh_deliverable: [],
    //               project_no: '20240410000001',
    //               is_last_level: true,
    //             },
    //             {
    //               task_name: 'B2-1',
    //               is_root_task: false,
    //               upper_level_task_no: '12',
    //               moh_attachment: [],
    //               task_no: '13',
    //               manual_assignment_delivery_plm: [],
    //               pcc_wbs_plan_changes: [],
    //               manual_assignment_delivery: [],
    //               root_task_no: '2',
    //               manual_assignment_attachment: [],
    //               sequence: 1,
    //               moh_deliverable: [],
    //               project_no: '20240410000001',
    //               is_last_level: false,
    //             },
    //             {
    //               task_name: 'B2',
    //               is_root_task: false,
    //               upper_level_task_no: '2',
    //               moh_attachment: [],
    //               task_no: '12',
    //               manual_assignment_delivery_plm: [],
    //               pcc_wbs_plan_changes: [],
    //               manual_assignment_delivery: [],
    //               root_task_no: '2',
    //               manual_assignment_attachment: [],
    //               sequence: 2,
    //               moh_deliverable: [],
    //               project_no: '20240410000001',
    //               is_last_level: false,
    //             },
    //             {
    //               task_name: 'B',
    //               is_root_task: true,
    //               upper_level_task_no: '2',
    //               moh_attachment: [],
    //               task_no: '2',
    //               manual_assignment_delivery_plm: [],
    //               pcc_wbs_plan_changes: [],
    //               manual_assignment_delivery: [],
    //               root_task_no: '2',
    //               manual_assignment_attachment: [],
    //               sequence: 2,
    //               moh_deliverable: [],
    //               project_no: '20240410000001',
    //               is_last_level: false,
    //             },
    //             {
    //               task_name: 'B2-1-1',
    //               manual_assignment_sample_delivery: [
    //                 {
    //                   category_id: 'manualAssignmentSampleDelivery',
    //                   size: 0,
    //                   upload_user_id: 'dcp012',
    //                   name: '交付物样板.txt',
    //                   id: 'b37ac2d6-89e2-43fb-9899-21401e91271d',
    //                   upload_user_name: '采购员小白',
    //                   row_data: 'LPC20240410001;14',
    //                   category: 'manualAssignmentSampleDelivery',
    //                   create_date: '2024-04-10 15:47:16',
    //                 },
    //               ],
    //               is_root_task: false,
    //               upper_level_task_no: '13',
    //               moh_attachment: [
    //                 {
    //                   category_id: '3936606d-d79e-4209-8ed1-9ea0f900051e',
    //                   size: 3332,
    //                   upload_user_id: 'dcp012',
    //                   name: '附件数据结构',
    //                   id: '14ef6220-9699-4d1a-a857-cf75d29553f0',
    //                   upload_user_name: '采购员小白',
    //                   row_data: '20240410000001;14;',
    //                   category: 'mohAttachment',
    //                   create_date: '2024-04-11 09:59:20',
    //                 },
    //                 {
    //                   category_id: '3936606d-d79e-4209-8ed1-9ea0f900051e',
    //                   size: 0,
    //                   upload_user_id: 'dcp012',
    //                   name: '工单工时的附件.txt',
    //                   id: '8cb778b7-f2c9-4e62-9f3b-a0829fab9673',
    //                   upload_user_name: '采购员小白',
    //                   row_data: '20240410000001;14;',
    //                   category: 'mohAttachment',
    //                   create_date: '2024-04-11 09:59:20',
    //                 },
    //               ],
    //               task_no: '14',
    //               manual_assignment_delivery_plm: [],
    //               pcc_wbs_plan_changes: [
    //                 {
    //                   category_id: 'pcc_wbs_planChanges',
    //                   size: 0,
    //                   upload_user_id: 'dcp012',
    //                   name: '任务变更附件.txt',
    //                   id: 'aaee3363-8b18-474b-bbe0-b678708b253c',
    //                   upload_user_name: '采购员小白',
    //                   row_data: '20240410000001;',
    //                   category: 'pcc_wbs_planChanges',
    //                   create_date: '2024-04-11 09:53:04',
    //                 },
    //               ],
    //               manual_assignment_delivery: [],
    //               root_task_no: '2',
    //               manual_assignment_attachment: [],
    //               sequence: 1,
    //               moh_deliverable: [
    //                 {
    //                   category_id: '3ed76ac5-de71-45c4-9776-e1bcc70595c5',
    //                   size: 0,
    //                   upload_user_id: 'dcp012',
    //                   name: '工单工时的交付物.txt',
    //                   id: 'e9125c31-c014-4d62-8015-bf0dcdeae11c',
    //                   upload_user_name: '采购员小白',
    //                   row_data: '20240410000001;14;',
    //                   category: 'mohDeliverable',
    //                   create_date: '2024-04-11 09:59:20',
    //                 },
    //                 {
    //                   category_id: '3ed76ac5-de71-45c4-9776-e1bcc70595c5',
    //                   size: 3332,
    //                   upload_user_id: 'dcp012',
    //                   name: '附件数据结构',
    //                   id: 'f0ff6190-d907-42cb-ac20-7a5b0e73b36b',
    //                   upload_user_name: '采购员小白',
    //                   row_data: '20240410000001;14;',
    //                   category: 'mohDeliverable',
    //                   create_date: '2024-04-11 09:59:20',
    //                 },
    //               ],
    //               project_no: '20240410000001',
    //               is_last_level: true,
    //             },
    //             {
    //               task_name: 'B2-1-2',
    //               manual_assignment_sample_delivery: [
    //                 {
    //                   category_id: 'manualAssignmentSampleDelivery',
    //                   size: 0,
    //                   upload_user_id: 'dcp012',
    //                   name: '交付物样板.txt',
    //                   id: 'e140416f-1017-4646-9d43-9831933f7dd1',
    //                   upload_user_name: '采购员小白',
    //                   row_data: '20240410000001;15',
    //                   category: 'manualAssignmentSampleDelivery',
    //                   create_date: '2024-04-10 18:07:18',
    //                 },
    //               ],
    //               is_root_task: false,
    //               upper_level_task_no: '13',
    //               moh_attachment: [],
    //               task_no: '15',
    //               manual_assignment_delivery_plm: [],
    //               pcc_wbs_plan_changes: [],
    //               manual_assignment_delivery: [],
    //               root_task_no: '2',
    //               manual_assignment_attachment: [],
    //               sequence: 2,
    //               moh_deliverable: [],
    //               project_no: '20240410000001',
    //               is_last_level: true,
    //             },
    //             {
    //               task_name: 'C',
    //               is_root_task: true,
    //               upper_level_task_no: '3',
    //               moh_attachment: [],
    //               task_no: '3',
    //               manual_assignment_delivery_plm: [],
    //               pcc_wbs_plan_changes: [],
    //               manual_assignment_delivery: [],
    //               root_task_no: '3',
    //               manual_assignment_attachment: [],
    //               sequence: 3,
    //               moh_deliverable: [],
    //               project_no: '20240410000001',
    //               is_last_level: false,
    //             },
    //             {
    //               task_name: 'C1',
    //               manual_assignment_sample_delivery: [
    //                 {
    //                   category_id: 'manualAssignmentSampleDelivery',
    //                   size: 0,
    //                   upload_user_id: 'dcp012',
    //                   name: '交付物样板.txt',
    //                   id: '2dce047b-1666-4388-b08b-af2af126371e',
    //                   upload_user_name: '采购员小白',
    //                   row_data: 'LPC20240410001;undefined',
    //                   category: 'manualAssignmentSampleDelivery',
    //                   create_date: '2024-04-10 15:48:47',
    //                 },
    //               ],
    //               is_root_task: false,
    //               upper_level_task_no: '3',
    //               moh_attachment: [],
    //               task_no: '17',
    //               manual_assignment_delivery_plm: [],
    //               pcc_wbs_plan_changes: [],
    //               manual_assignment_delivery: [],
    //               root_task_no: '3',
    //               manual_assignment_attachment: [],
    //               sequence: 1,
    //               moh_deliverable: [],
    //               project_no: '20240410000001',
    //               is_last_level: false,
    //             },
    //             {
    //               task_name: 'E',
    //               manual_assignment_sample_delivery: [
    //                 {
    //                   category_id: 'manualAssignmentSampleDelivery',
    //                   size: 0,
    //                   upload_user_id: 'dcp012',
    //                   name: '交付物样板.txt',
    //                   id: 'dc29b0de-ba94-411e-be90-e9cad112f604',
    //                   upload_user_name: '采购员小白',
    //                   row_data: '20240410000001;undefined',
    //                   category: 'manualAssignmentSampleDelivery',
    //                   create_date: '2024-04-11 11:14:58',
    //                 },
    //                 {
    //                   category_id: 'manualAssignmentSampleDelivery',
    //                   size: 3332,
    //                   upload_user_id: 'dcp012',
    //                   name: '附件数据结构',
    //                   id: 'd6aad069-e22c-4050-9754-a161fe9ff57b',
    //                   upload_user_name: '采购员小白',
    //                   row_data: '20240410000001;undefined',
    //                   category: 'manualAssignmentSampleDelivery',
    //                   create_date: '2024-04-11 11:15:06',
    //                 },
    //               ],
    //               is_root_task: true,
    //               upper_level_task_no: '21',
    //               moh_attachment: [],
    //               task_no: '21',
    //               manual_assignment_delivery_plm: [],
    //               pcc_wbs_plan_changes: [],
    //               manual_assignment_delivery: [],
    //               root_task_no: '21',
    //               manual_assignment_attachment: [],
    //               sequence: 5,
    //               moh_deliverable: [],
    //               project_no: '20240410000001',
    //               is_last_level: true,
    //             },
    //           ],
    //           'Recursion递归【单独计算】 ms:': 0.428375,
    //           'QUERY_SCOPE_ALL_1 ms:': 36846.625208,
    //           project_change_attachment: [
    //             {
    //               project_no: '20240410000001',
    //               old_change_version: 6,
    //               project_name: '附件重构001',
    //               change_version: 7,
    //               pcc_project_change_task: [
    //                 {
    //                   category_id: 'pcc_project_change_task',
    //                   size: 0,
    //                   upload_user_id: 'dcp012',
    //                   name: '项目变更附件.txt',
    //                   id: '4400ff8b-7fdd-448c-9460-b31cc495b22d',
    //                   upload_user_name: '采购员小白',
    //                   row_data: '20240410000001;',
    //                   category: 'pcc_project_change_task',
    //                   create_date: '2024-04-11 11:02:40',
    //                 },
    //                 {
    //                   category_id: 'pcc_project_change_task',
    //                   size: 0,
    //                   upload_user_id: 'dcp012',
    //                   name: '项目变更附件.txt',
    //                   id: '48ff06b2-9ee9-4af9-80e8-5bdcb8886a89',
    //                   upload_user_name: '采购员小白',
    //                   row_data: '20240410000001;',
    //                   category: 'pcc_project_change_task',
    //                   create_date: '2024-04-11 11:02:43',
    //                 },
    //               ],
    //             },
    //           ],
    //           project_attachment: [
    //             {
    //               project_no: '20240410000001',
    //               athena_launch_special_project_create: [
    //                 {
    //                   category_id: 'athena_LaunchSpecialProject_create',
    //                   size: 4669,
    //                   upload_user_id: 'dcp012',
    //                   name: '1222.xlsx',
    //                   id: '9e7ca1b7-9c72-44f6-b328-05466984b1ac',
    //                   upload_user_name: '采购员小白',
    //                   row_data: '20240410000001;',
    //                   category: 'athena_LaunchSpecialProject_create',
    //                   create_date: '2024-04-11 15:42:23',
    //                 },
    //               ],
    //               project_name: '附件重构001',
    //               pcc_project_status_change: [],
    //             },
    //             {
    //               project_no: '20240410000001',
    //               athena_launch_special_project_create: [],
    //               project_name: '附件重构001[V3]-暂停项目',
    //               pcc_project_status_change: [
    //                 {
    //                   category_id: 'pcc_project_status_change',
    //                   size: 0,
    //                   upload_user_id: 'dcp012',
    //                   name: '项目状态变更附件.txt',
    //                   id: 'd0252afb-718d-4dd2-9a4e-bc6a1a0df41f',
    //                   upload_user_name: '采购员小白',
    //                   row_data: '20240410000001;',
    //                   category: 'pcc_project_status_change',
    //                   create_date: '2024-04-10 18:13:42',
    //                 },
    //               ],
    //             },
    //             {
    //               project_no: '20240410000001',
    //               athena_launch_special_project_create: [],
    //               project_name: '附件重构001[V3]-继续项目',
    //               pcc_project_status_change: [
    //                 {
    //                   category_id: 'pcc_project_status_change',
    //                   size: 0,
    //                   upload_user_id: 'dcp012',
    //                   name: '项目状态变更附件.txt',
    //                   id: '4547dde5-7aee-48e5-82b2-7be50d8b147e',
    //                   upload_user_name: '采购员小白',
    //                   row_data: '20240410000001;',
    //                   category: 'pcc_project_status_change',
    //                   create_date: '2024-04-10 18:14:16',
    //                 },
    //               ],
    //             },
    //           ],
    //           'QUERY_SCOPE_ALL_2_ADD_3 ms:': 37544.521417,
    //         }
    //       );
    //     })
    //   )
    //   .toPromise();
    // return this.http
    //   .post('http://127.0.0.1:4523/m1/3569931-0-default/test', {})
    //   .pipe(
    //     map((res: any) => {
    //       return {
    //         'projectInfoList ms:': 35817.87425,
    //         task_attachment: [
    //           {
    //             task_name: 'A',
    //             is_root_task: true,
    //             upper_level_task_no: '1',
    //             moh_attachment: [],
    //             task_no: '1',
    //             manual_assignment_delivery_plm: [],
    //             pcc_wbs_plan_changes: [],
    //             manual_assignment_delivery: [],
    //             root_task_no: '1',
    //             manual_assignment_attachment: [],
    //             sequence: 1,
    //             moh_deliverable: [],
    //             project_no: '20240410000001',
    //             is_last_level: false,
    //           },
    //           {
    //             task_name: 'A1',
    //             manual_assignment_sample_delivery: [
    //               {
    //                 category_id: 'manualAssignmentSampleDelivery',
    //                 size: 0,
    //                 upload_user_id: 'dcp012',
    //                 name: '交付物样板.txt',
    //                 id: '840f05b5-bcb6-46f7-8303-5f4e0c9c3bf5',
    //                 upload_user_name: '采购员小白',
    //                 row_data: 'LPC20240410001;undefined',
    //                 category: 'manualAssignmentSampleDelivery',
    //                 create_date: '2024-04-10 15:34:06',
    //               },
    //               {
    //                 category_id: 'manualAssignmentSampleDelivery',
    //                 size: 0,
    //                 upload_user_id: 'dcp012',
    //                 name: '交付物样板.txt',
    //                 id: '315622c0-c12a-48c6-9645-d9dd0e55deac',
    //                 upload_user_name: '采购员小白',
    //                 row_data: '20240410000001;5',
    //                 category: 'manualAssignmentSampleDelivery',
    //                 create_date: '2024-04-10 16:30:29',
    //               },
    //             ],
    //             is_root_task: false,
    //             upper_level_task_no: '1',
    //             moh_attachment: [],
    //             task_no: '5',
    //             manual_assignment_delivery_plm: [],
    //             pcc_wbs_plan_changes: [],
    //             manual_assignment_delivery: [],
    //             root_task_no: '1',
    //             manual_assignment_attachment: [],
    //             sequence: 1,
    //             moh_deliverable: [],
    //             project_no: '20240410000001',
    //             is_last_level: false,
    //           },
    //           {
    //             task_name: 'A2',
    //             is_root_task: false,
    //             upper_level_task_no: '1',
    //             moh_attachment: [],
    //             task_no: '7',
    //             manual_assignment_delivery_plm: [],
    //             pcc_wbs_plan_changes: [],
    //             manual_assignment_delivery: [],
    //             root_task_no: '1',
    //             manual_assignment_attachment: [],
    //             sequence: 2,
    //             moh_deliverable: [],
    //             project_no: '20240410000001',
    //             is_last_level: false,
    //           },
    //           {
    //             task_name: 'A2-1',
    //             manual_assignment_sample_delivery: [
    //               {
    //                 category_id: 'manualAssignmentSampleDelivery',
    //                 size: 0,
    //                 upload_user_id: 'dcp012',
    //                 name: '交付物样板.txt',
    //                 id: 'e41b1de8-5779-4f38-8a88-4cd2370b6f5d',
    //                 upload_user_name: '采购员小白',
    //                 row_data: 'LPC20240410001;8',
    //                 category: 'manualAssignmentSampleDelivery',
    //                 create_date: '2024-04-10 15:47:36',
    //               },
    //             ],
    //             is_root_task: false,
    //             upper_level_task_no: '7',
    //             moh_attachment: [],
    //             task_no: '8',
    //             manual_assignment_delivery_plm: [],
    //             pcc_wbs_plan_changes: [
    //               {
    //                 category_id: 'pcc_wbs_planChanges',
    //                 size: 0,
    //                 upload_user_id: 'dcp012',
    //                 name: '任务变更附件.txt',
    //                 id: '1beb34d3-bb9a-4dd3-93b4-ee9ca1376e9d',
    //                 upload_user_name: '采购员小白',
    //                 row_data: '20240410000001;',
    //                 category: 'pcc_wbs_planChanges',
    //                 create_date: '2024-04-11 09:40:52',
    //               },
    //             ],
    //             manual_assignment_delivery: [
    //               {
    //                 category_id: 'e30a83cf-b4b9-41f6-9015-bfe9ecc3f356',
    //                 size: 0,
    //                 upload_user_id: 'dcp012',
    //                 name: '交付物.txt',
    //                 id: '8de86a09-ce08-447a-99c5-cc376db1bc94',
    //                 upload_user_name: '采购员小白',
    //                 row_data: '20240410000001;8;',
    //                 category: 'manualAssignmentDelivery',
    //                 create_date: '2024-04-10 17:44:01',
    //               },
    //               {
    //                 category_id: 'e30a83cf-b4b9-41f6-9015-bfe9ecc3f356',
    //                 size: 3332,
    //                 upload_user_id: 'dcp012',
    //                 name: '附件数据结构',
    //                 id: '92bdc880-aad2-4477-8e83-6b2e31bb597c',
    //                 upload_user_name: '采购员小白',
    //                 row_data: '20240410000001;8;',
    //                 category: 'manualAssignmentDelivery',
    //                 create_date: '2024-04-10 17:44:01',
    //               },
    //             ],
    //             root_task_no: '1',
    //             manual_assignment_attachment: [
    //               {
    //                 category_id: '3dec5e77-0489-4a7b-a97f-baf77ced1f7c',
    //                 size: 40960,
    //                 upload_user_id: 'dcp012',
    //                 name: '任务附件.dps',
    //                 id: '837a9e42-9c93-436b-8a0a-00ade8f278f1',
    //                 upload_user_name: '采购员小白',
    //                 row_data: '20240410000001;8;',
    //                 category: 'manualAssignmentAttachment',
    //                 create_date: '2024-04-10 17:44:01',
    //               },
    //               {
    //                 category_id: '3dec5e77-0489-4a7b-a97f-baf77ced1f7c',
    //                 size: 3332,
    //                 upload_user_id: 'dcp012',
    //                 name: '附件数据结构',
    //                 id: 'ef210a46-8466-4b0b-a606-6674aea7e7f9',
    //                 upload_user_name: '采购员小白',
    //                 row_data: '20240410000001;8;',
    //                 category: 'manualAssignmentAttachment',
    //                 create_date: '2024-04-10 17:44:01',
    //               },
    //             ],
    //             sequence: 1,
    //             moh_deliverable: [],
    //             project_no: '20240410000001',
    //             is_last_level: true,
    //           },
    //           {
    //             task_name: 'B2-1',
    //             is_root_task: false,
    //             upper_level_task_no: '12',
    //             moh_attachment: [],
    //             task_no: '13',
    //             manual_assignment_delivery_plm: [],
    //             pcc_wbs_plan_changes: [],
    //             manual_assignment_delivery: [],
    //             root_task_no: '2',
    //             manual_assignment_attachment: [],
    //             sequence: 1,
    //             moh_deliverable: [],
    //             project_no: '20240410000001',
    //             is_last_level: false,
    //           },
    //           {
    //             task_name: 'B2',
    //             is_root_task: false,
    //             upper_level_task_no: '2',
    //             moh_attachment: [],
    //             task_no: '12',
    //             manual_assignment_delivery_plm: [],
    //             pcc_wbs_plan_changes: [],
    //             manual_assignment_delivery: [],
    //             root_task_no: '2',
    //             manual_assignment_attachment: [],
    //             sequence: 2,
    //             moh_deliverable: [],
    //             project_no: '20240410000001',
    //             is_last_level: false,
    //           },
    //           {
    //             task_name: 'B',
    //             is_root_task: true,
    //             upper_level_task_no: '2',
    //             moh_attachment: [],
    //             task_no: '2',
    //             manual_assignment_delivery_plm: [],
    //             pcc_wbs_plan_changes: [],
    //             manual_assignment_delivery: [],
    //             root_task_no: '2',
    //             manual_assignment_attachment: [],
    //             sequence: 2,
    //             moh_deliverable: [],
    //             project_no: '20240410000001',
    //             is_last_level: false,
    //           },
    //           {
    //             task_name: 'B2-1-1',
    //             manual_assignment_sample_delivery: [
    //               {
    //                 category_id: 'manualAssignmentSampleDelivery',
    //                 size: 0,
    //                 upload_user_id: 'dcp012',
    //                 name: '交付物样板.txt',
    //                 id: 'b37ac2d6-89e2-43fb-9899-21401e91271d',
    //                 upload_user_name: '采购员小白',
    //                 row_data: 'LPC20240410001;14',
    //                 category: 'manualAssignmentSampleDelivery',
    //                 create_date: '2024-04-10 15:47:16',
    //               },
    //             ],
    //             is_root_task: false,
    //             upper_level_task_no: '13',
    //             moh_attachment: [
    //               {
    //                 category_id: '3936606d-d79e-4209-8ed1-9ea0f900051e',
    //                 size: 3332,
    //                 upload_user_id: 'dcp012',
    //                 name: '附件数据结构',
    //                 id: '14ef6220-9699-4d1a-a857-cf75d29553f0',
    //                 upload_user_name: '采购员小白',
    //                 row_data: '20240410000001;14;',
    //                 category: 'mohAttachment',
    //                 create_date: '2024-04-11 09:59:20',
    //               },
    //               {
    //                 category_id: '3936606d-d79e-4209-8ed1-9ea0f900051e',
    //                 size: 0,
    //                 upload_user_id: 'dcp012',
    //                 name: '工单工时的附件.txt',
    //                 id: '8cb778b7-f2c9-4e62-9f3b-a0829fab9673',
    //                 upload_user_name: '采购员小白',
    //                 row_data: '20240410000001;14;',
    //                 category: 'mohAttachment',
    //                 create_date: '2024-04-11 09:59:20',
    //               },
    //             ],
    //             task_no: '14',
    //             manual_assignment_delivery_plm: [],
    //             pcc_wbs_plan_changes: [
    //               {
    //                 category_id: 'pcc_wbs_planChanges',
    //                 size: 0,
    //                 upload_user_id: 'dcp012',
    //                 name: '任务变更附件.txt',
    //                 id: 'aaee3363-8b18-474b-bbe0-b678708b253c',
    //                 upload_user_name: '采购员小白',
    //                 row_data: '20240410000001;',
    //                 category: 'pcc_wbs_planChanges',
    //                 create_date: '2024-04-11 09:53:04',
    //               },
    //             ],
    //             manual_assignment_delivery: [],
    //             root_task_no: '2',
    //             manual_assignment_attachment: [],
    //             sequence: 1,
    //             moh_deliverable: [
    //               {
    //                 category_id: '3ed76ac5-de71-45c4-9776-e1bcc70595c5',
    //                 size: 0,
    //                 upload_user_id: 'dcp012',
    //                 name: '工单工时的交付物.txt',
    //                 id: 'e9125c31-c014-4d62-8015-bf0dcdeae11c',
    //                 upload_user_name: '采购员小白',
    //                 row_data: '20240410000001;14;',
    //                 category: 'mohDeliverable',
    //                 create_date: '2024-04-11 09:59:20',
    //               },
    //               {
    //                 category_id: '3ed76ac5-de71-45c4-9776-e1bcc70595c5',
    //                 size: 3332,
    //                 upload_user_id: 'dcp012',
    //                 name: '附件数据结构',
    //                 id: 'f0ff6190-d907-42cb-ac20-7a5b0e73b36b',
    //                 upload_user_name: '采购员小白',
    //                 row_data: '20240410000001;14;',
    //                 category: 'mohDeliverable',
    //                 create_date: '2024-04-11 09:59:20',
    //               },
    //             ],
    //             project_no: '20240410000001',
    //             is_last_level: true,
    //           },
    //           {
    //             task_name: 'B2-1-2',
    //             manual_assignment_sample_delivery: [
    //               {
    //                 category_id: 'manualAssignmentSampleDelivery',
    //                 size: 0,
    //                 upload_user_id: 'dcp012',
    //                 name: '交付物样板.txt',
    //                 id: 'e140416f-1017-4646-9d43-9831933f7dd1',
    //                 upload_user_name: '采购员小白',
    //                 row_data: '20240410000001;15',
    //                 category: 'manualAssignmentSampleDelivery',
    //                 create_date: '2024-04-10 18:07:18',
    //               },
    //             ],
    //             is_root_task: false,
    //             upper_level_task_no: '13',
    //             moh_attachment: [],
    //             task_no: '15',
    //             manual_assignment_delivery_plm: [],
    //             pcc_wbs_plan_changes: [],
    //             manual_assignment_delivery: [],
    //             root_task_no: '2',
    //             manual_assignment_attachment: [],
    //             sequence: 2,
    //             moh_deliverable: [],
    //             project_no: '20240410000001',
    //             is_last_level: true,
    //           },
    //           {
    //             task_name: 'C',
    //             is_root_task: true,
    //             upper_level_task_no: '3',
    //             moh_attachment: [],
    //             task_no: '3',
    //             manual_assignment_delivery_plm: [],
    //             pcc_wbs_plan_changes: [],
    //             manual_assignment_delivery: [],
    //             root_task_no: '3',
    //             manual_assignment_attachment: [],
    //             sequence: 3,
    //             moh_deliverable: [],
    //             project_no: '20240410000001',
    //             is_last_level: false,
    //           },
    //           {
    //             task_name: 'C1',
    //             manual_assignment_sample_delivery: [
    //               {
    //                 category_id: 'manualAssignmentSampleDelivery',
    //                 size: 0,
    //                 upload_user_id: 'dcp012',
    //                 name: '交付物样板.txt',
    //                 id: '2dce047b-1666-4388-b08b-af2af126371e',
    //                 upload_user_name: '采购员小白',
    //                 row_data: 'LPC20240410001;undefined',
    //                 category: 'manualAssignmentSampleDelivery',
    //                 create_date: '2024-04-10 15:48:47',
    //               },
    //             ],
    //             is_root_task: false,
    //             upper_level_task_no: '3',
    //             moh_attachment: [],
    //             task_no: '17',
    //             manual_assignment_delivery_plm: [],
    //             pcc_wbs_plan_changes: [],
    //             manual_assignment_delivery: [],
    //             root_task_no: '3',
    //             manual_assignment_attachment: [],
    //             sequence: 1,
    //             moh_deliverable: [],
    //             project_no: '20240410000001',
    //             is_last_level: false,
    //           },
    //           {
    //             task_name: 'E',
    //             manual_assignment_sample_delivery: [
    //               {
    //                 category_id: 'manualAssignmentSampleDelivery',
    //                 size: 0,
    //                 upload_user_id: 'dcp012',
    //                 name: '交付物样板.txt',
    //                 id: 'dc29b0de-ba94-411e-be90-e9cad112f604',
    //                 upload_user_name: '采购员小白',
    //                 row_data: '20240410000001;undefined',
    //                 category: 'manualAssignmentSampleDelivery',
    //                 create_date: '2024-04-11 11:14:58',
    //               },
    //               {
    //                 category_id: 'manualAssignmentSampleDelivery',
    //                 size: 3332,
    //                 upload_user_id: 'dcp012',
    //                 name: '附件数据结构',
    //                 id: 'd6aad069-e22c-4050-9754-a161fe9ff57b',
    //                 upload_user_name: '采购员小白',
    //                 row_data: '20240410000001;undefined',
    //                 category: 'manualAssignmentSampleDelivery',
    //                 create_date: '2024-04-11 11:15:06',
    //               },
    //             ],
    //             is_root_task: true,
    //             upper_level_task_no: '21',
    //             moh_attachment: [],
    //             task_no: '21',
    //             manual_assignment_delivery_plm: [],
    //             pcc_wbs_plan_changes: [],
    //             manual_assignment_delivery: [],
    //             root_task_no: '21',
    //             manual_assignment_attachment: [],
    //             sequence: 5,
    //             moh_deliverable: [],
    //             project_no: '20240410000001',
    //             is_last_level: true,
    //           },
    //         ],
    //         'Recursion递归【单独计算】 ms:': 0.428375,
    //         'QUERY_SCOPE_ALL_1 ms:': 36846.625208,
    //         project_change_attachment: [
    //           {
    //             project_no: '20240410000001',
    //             old_change_version: 6,
    //             project_name: '附件重构001',
    //             change_version: 7,
    //             pcc_project_change_task: [
    //               {
    //                 category_id: 'pcc_project_change_task',
    //                 size: 0,
    //                 upload_user_id: 'dcp012',
    //                 name: '项目变更附件.txt',
    //                 id: '4400ff8b-7fdd-448c-9460-b31cc495b22d',
    //                 upload_user_name: '采购员小白',
    //                 row_data: '20240410000001;',
    //                 category: 'pcc_project_change_task',
    //                 create_date: '2024-04-11 11:02:40',
    //               },
    //               {
    //                 category_id: 'pcc_project_change_task',
    //                 size: 0,
    //                 upload_user_id: 'dcp012',
    //                 name: '项目变更附件.txt',
    //                 id: '48ff06b2-9ee9-4af9-80e8-5bdcb8886a89',
    //                 upload_user_name: '采购员小白',
    //                 row_data: '20240410000001;',
    //                 category: 'pcc_project_change_task',
    //                 create_date: '2024-04-11 11:02:43',
    //               },
    //             ],
    //           },
    //         ],
    //         project_attachment: [
    //           {
    //             project_no: '20240410000001',
    //             athena_launch_special_project_create: [
    //               {
    //                 category_id: 'athena_LaunchSpecialProject_create',
    //                 size: 4669,
    //                 upload_user_id: 'dcp012',
    //                 name: '1222.xlsx',
    //                 id: '9e7ca1b7-9c72-44f6-b328-05466984b1ac',
    //                 upload_user_name: '采购员小白',
    //                 row_data: '20240410000001;',
    //                 category: 'athena_LaunchSpecialProject_create',
    //                 create_date: '2024-04-11 15:42:23',
    //               },
    //             ],
    //             project_name: '附件重构001',
    //             pcc_project_status_change: [],
    //           },
    //           {
    //             project_no: '20240410000001',
    //             athena_launch_special_project_create: [],
    //             project_name: '附件重构001[V3]-暂停项目',
    //             pcc_project_status_change: [
    //               {
    //                 category_id: 'pcc_project_status_change',
    //                 size: 0,
    //                 upload_user_id: 'dcp012',
    //                 name: '项目状态变更附件.txt',
    //                 id: 'd0252afb-718d-4dd2-9a4e-bc6a1a0df41f',
    //                 upload_user_name: '采购员小白',
    //                 row_data: '20240410000001;',
    //                 category: 'pcc_project_status_change',
    //                 create_date: '2024-04-10 18:13:42',
    //               },
    //             ],
    //           },
    //           {
    //             project_no: '20240410000001',
    //             athena_launch_special_project_create: [],
    //             project_name: '附件重构001[V3]-继续项目',
    //             pcc_project_status_change: [
    //               {
    //                 category_id: 'pcc_project_status_change',
    //                 size: 0,
    //                 upload_user_id: 'dcp012',
    //                 name: '项目状态变更附件.txt',
    //                 id: '4547dde5-7aee-48e5-82b2-7be50d8b147e',
    //                 upload_user_name: '采购员小白',
    //                 row_data: '20240410000001;',
    //                 category: 'pcc_project_status_change',
    //                 create_date: '2024-04-10 18:14:16',
    //               },
    //             ],
    //           },
    //         ],
    //         'QUERY_SCOPE_ALL_2_ADD_3 ms:': 37544.521417,
    //       };
    //     })
    //   )
    //   .toPromise();
    return this.commonService
      .getInvData('project.attachment.get', {
        query_scope: params.query_scope, // 1、任务附件  2、项目附件  3、项目变更附件  ALL、全部
        project_info: [
          {
            project_no: params.project_no,
          },
        ],
      })
      .pipe(
        map((res: any) => {
          return res.data || {};
        })
      )
      .toPromise();
  }
}
